import { useState, useRef } from "react";
import { clsx } from "keycloakify/tools/clsx";
import type { PageProps } from "keycloakify/login/pages/PageProps";
import type { KcContext } from "../kcContext";
import type { I18n } from "../i18n";
import logo from "../assets/logoHCM.png";
import { useGetClassName } from "keycloakify/login/lib/useGetClassName";

export default function LoginOtp(props: PageProps<Extract<KcContext, { pageId: "login-otp.ftl" }>, I18n>) 
{
    const { kcContext, i18n, doUseDefaultCss, Template, classes } = props;
    const { url, messagesPerField } = kcContext;
    const { msg, msgStr } = i18n;
    const [isSubmitting, setIsSubmitting] = useState(false);
    const { getClassName } = useGetClassName({
        doUseDefaultCss,
        classes
    });

    // 6-digit code state
    const [code, setCode] = useState(["", "", "", "", "", ""]);
    const inputsRef = useRef<Array<HTMLInputElement | null>>([]);

    const handleCodeChange = (idx: number, value: string) => {
        if (!/^[0-9]?$/.test(value)) return; // Only allow single digit
        const newCode = [...code];
        newCode[idx] = value;
        setCode(newCode);

        // Move to next input if filled
        if (value && idx < 5) {
            inputsRef.current[idx + 1]?.focus();
        }
    };

    // Handle backspace to move focus
    const handleKeyDown = (idx: number, e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === "Backspace" && !code[idx] && idx > 0) {
            inputsRef.current[idx - 1]?.focus();
        }
    };

    // Combine code for submission
    const handleSubmit = (e: React.FormEvent) => {
        setIsSubmitting(true);
        // Set hidden input value before submit
        (document.getElementById("otp-hidden") as HTMLInputElement).value = code.join("");
        // Let form submit
    };

    return (
        <Template
            kcContext={kcContext}
            i18n={i18n}
            doUseDefaultCss={doUseDefaultCss}
            classes={classes}
            displayMessage={messagesPerField.existsError("totp")}
            headerNode={msg("loginTotpTitle") || "Enter code from Microsoft Authenticator"}
        >
            <div style={{ height: "300px", paddingBottom: "100px" }}>
                <div>
                    <img src={logo} style={{ width: '150px', height: '30px', marginRight: '10px', marginBottom: '20px' }} />
                    <div style={{ fontWeight: 400, fontSize: '25px', lineHeight: '40px', color: '#253053', textAlign: 'left', marginBottom: '20px' }}>
                        Two-factor Authentication
                    </div>
                    <div style={{ color: "#666", fontSize: '15px', marginBottom: 24}}>
                        To verify your identity, enter the code generated by your two-factor authentication app.
                    </div>
                </div>
                <form
                    id="kc-otp-login-form"
                    className={clsx("kcFormClass")}
                    action={url.loginAction}
                    onSubmit={handleSubmit}
                    method="post"
                >
                    <div className={clsx("kcFormGroupClass")}>
                        <div className={clsx("kcLabelWrapperClass")}>
                            <label htmlFor="otp" className={clsx("kcLabelClass")} style={{ fontSize: '16px', color: '#253053', fontWeight: '600' }}>
                                We’ve Sent you a code
                            </label>
                        </div>
                        <div className="otp-code-inputs">
                            {code.map((digit, idx) => (
                                <input
                                    key={idx}
                                    type="text"
                                    inputMode="numeric"
                                    maxLength={1}
                                    className="otp-code-input"
                                    value={digit}
                                    ref={el => (inputsRef.current[idx] = el)}
                                    onChange={e => handleCodeChange(idx, e.target.value.replace(/[^0-9]/, ""))}
                                    onKeyDown={e => handleKeyDown(idx, e)}
                                    autoFocus={idx === 0}
                                    name={`code-${idx}`}
                                    style={{ textAlign: "center" }}
                                />
                            ))}
                        </div>
                        {/* Hidden input for form submission */}
                        <input type="hidden" id="otp-hidden" name="otp" value={code.join("")} />
                        {messagesPerField.existsError("totp") && (
                            <span
                                id="input-error-otp-code"
                                className={clsx("kcInputErrorMessageClass")}
                                aria-live="polite"
                            >
                                {messagesPerField.get("totp")}
                            </span>
                        )}
                    </div>

                    <div style={{ textAlign: "center" }}>
                        <div style={{ marginTop: "50px" }}>
                            <input
                                className={clsx(
                                    getClassName("kcButtonClass"),
                                    getClassName("kcButtonBlockClass"),
                                    getClassName("kcButtonLargeClass")
                                )}
                                name="login"
                                id="kc-login"
                                type="submit"
                                value="Verify"
                                disabled={isSubmitting}
                                style={{ backgroundColor: '#2C82F9', borderRadius: '6px', color: '#FFFFFF' }}
                            />
                        </div>
                         <div style={{ marginTop: "10px" }}>
                            <a
                                href={url.loginRestartFlowUrl}
                                className={clsx("kcButtonClass", "kcButtonDefaultClass", "kcButtonLargeClass")}
                                id="cancelTOTPBtn"
                                style={{ fontSize: '14px', color: '#2C82F9', fontWeight: '400' }}
                            >
                                {msg("doCancel")}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </Template>
    );
}